name: R Package CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2.0"
      - name: Install Dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-4-dev libwebkitgtk-6.0-dev cmake swig
      - name: Install Dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install cmake swig
      - name: Install Dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install cmake swig
      - name: Build and Check
        run: R CMD build . && R CMD check RWebview_0.1.0.tar.gz --no-manual
